### PR TITLE
Milestone1 - Tic Tac Toe (Ruby)

### PR DESCRIPTION
**Pull request by brugobi**
## Here is the first part of the Tic Tac Toe Project

- Milestone 1: Creating an executable and structuring the folders (bin, lib) and main.rb file 

### Thank you

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
The project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team  
### You did a good job so far! Still, there are two more requirements missed:
* [x] Linter is not checking this Pull Request, make sure to add it to the repository and set up correctly.
* [x] The project should have a `lib` directory (with .gitkeep file OR any other **empty** file(s)). ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)). Make sure to add a file inside `lib` directory, because you won't be able to commit an empty folder otherwise.  

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by brugobi** [comment]
## All the issues have fixed

**Review by MarioDena — APPROVED** [review]
Hello Team great work implementing the requested changes!

## Project approved 

A a side note the empty files to keep folder structure on commits for github have a namming convention "gitkeep" Just a note. Cheers! 🦾

**Comment by brugobi** [comment]
@MarioDena thank you for your review and about the empty file this "gitkeep" name is not working...we tried many times but when We push it - the lib folder with the file can not be pushed. For the second milestone is working, but the first one is not. Do you have any idea why ?

**Comment by MarioDena** [comment]
> 
> 
> @MarioDena thank you for your review and about the empty file this "gitkeep" name is not working...we tried many times but when We push it - the lib folder with the file can not be pushed. For the second milestone is working, but the first one is not. Do you have any idea why ?

Hello! @brugobi  Well to be honest it happend to me one time. I added gitkeep to gitignore and even after removing it, it was not being pushed. Maybe a bug with the CLI? I't just a minor stuff if it's working on the second milestone, but could be fun to find out why. Maybe if I have some free time i'll look into it. Cheers!

**Pull request merged**
